<?xml version="1.0" encoding="utf-8" standalone="yes"?>

<!DOCTYPE employees [
<!ELEMENT employees (employee+)>
<!ELEMENT employee (firstName,lastName,age,employer+,address+)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT employer (name,startDate,endDate,position)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT address (street,streetNumber,city)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT streetNumber (#PCDATA)>
<!ELEMENT city (#PCDATA)>
]>


<employees>
  <employee>
    <firstName>Georgi</firstName>
		<lastName>Georgiev</lastName>
		<age>23</age>
		<employer>
			<name>EVO LTD.</name>
			<startDate>2008-03-10</startDate>
			<endDate>2009-08-01</endDate>
			<position>helpdesk/support</position>
		</employer><employer>
			<name>CLOUWAY LTD.</name>
			<startDate>2012-03-26</startDate>
			<endDate>2012-12-21</endDate>
			<position>junior software developer</position>
		</employer>
		<address>
			<street>Hristo Botev</street>
			<streetNumber>12</streetNumber>
			<city>Veliko Tarnovo</city>
		</address>
		<address>
			<street>Ivan Vazov</street>
			<streetNumber>23</streetNumber>
      <city>Sofia</city>
		</address>
	</employee>
  <employee>
		<firstName>Grisha</firstName>
    <lastName>Angelov</lastName>
		<age>23</age>
		<employer>
			<name>CLOUWAY LTD.</name>
			<startDate>2012-03-26</startDate>
			<endDate>2012-12-21</endDate>
      <position>software developer</position>
		</employer>
		<address>
			<street>Ruen</street>
      <streetNumber>3</streetNumber>
			<city>Polski Trymbesh</city>
		</address>
		<address>
      <street>Kosta Panica</street>
			<streetNumber>3</streetNumber>
			<city>Veliko Tarnovo</city>
		</address>
  </employee>
</employees>
